version: "3.8"

services: 
    db:
        image: mysql:5.7
        container_name: deno-db-dev
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        volumes: 
            # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_PASSWORD-testmoa}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-testmoa}
    api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        image: deno-api:dev
        container_name: deno-api-dev
        restart: always
        depends_on: 
            - db
        volumes: 
            - ./:/usr/app
        ports: 
            - ${PORT-5555}:${PORT-5555}
        environment: 
            - DB_HOST=${DB_HOST-db}
            - DB_USERNAME=${DB_USERNAME-root}
            - DB_DATABASE=${DB_DATABASE-testmoa}
            - DB_PASSWORD=${DB_PASSWORD-testmoa}
            - TOKEN_SECRET=${TOKEN_SECRET-secret}
            - PORT=${PORT-5555}

volumes:
    db-data:
        name: deno-db-dev-data