FROM denoland/deno:alpine

EXPOSE 5000

RUN deno install -qAf --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts

WORKDIR /usr/app

COPY . .

RUN deno cache --import-map=import_map.json src/deps.ts

RUN deno cache --import-map=import_map.json src/main.ts

ENTRYPOINT [ "/usr/local/bin/denon" ]

CMD [ "run", "--import-map=import_map.json", "--allow-net", "--allow-env", "--allow-read", "src/main.ts" ]